channels:
  - conda-forge
dependencies:
  - python=3.8
  - cairo
  - cairosvg
  - jedi=0.17.2
  - jupyter-book
  - jupyterlab
  - line_profiler
  - matplotlib
  - pandas
  - pillow
  - pip
  - sphinx
  - yarn
  - pip:
    - py5[jupyter]
