name: py5coding
channels:
  - conda-forge
dependencies:
  - python=3.10
  - colour
  - jpype1
  - jupyterlab
  - line_profiler
  - matplotlib
  - numpy
  - pillow
  - pip
  - shapely
  - trimesh
  - pip:
      - py5[extras]
